#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

~/.config/polybar/launch.sh --blocks &
picom --config ~/.config/picom/picom.conf &
#xidlehook --not-when-fullscreen --not-when-audio --timer 600 'betterlockscreen -l dimblur' '' &
nitrogen --restore &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
discord &

bspc monitor -d 1 2 3 4 5 6 7 

bspc config border_width         2
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Code desktop='^1'
bspc rule -a Brave desktop='^2'
bspc rule -a Spotify desktop='^3'
bspc rule -a discord desktop='^4'
