#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

~/.config/polybar/launch.sh &
nm-applet &
picom --config ~/.config/picom/picom.conf &
xidlehook --not-when-fullscreen --not-when-audio --timer 600 'betterlockscreen -l dimblur' '' &
nitrogen --restore &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#/usr/bin/gnome-keyring-daemon --start --components=secrets

## Tochpad Tapping and Natural Scrolling
xinput --set-prop "DELL083C:00 04F3:3088 Touchpad" "libinput Tapping Enabled" 1
xinput --set-prop "DELL083C:00 04F3:3088 Touchpad" "libinput Natural Scrolling Enabled" 1

bspc monitor eDP1 -d 1 2 3 4 5
bspc monitor HDMI1 -d 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Code desktop='^1'
bspc rule -a Brave desktop='^2'
bspc rule -a Spotify desktop='^3'
bspc rule -a discord desktop='^4'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
